import "../styles/globals.css";
import Head from "next/head";
import Provider from "@/context/Provider";

export default function App({ Component, pageProps }) {
  return (
    <Provider>
      <div className="min-h-screen flex justify-center items-center">
        <Head>
          <title>Todo App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <Component {...pageProps} />
      </div>
    </Provider>
  );
}
